# Звіт до роботи
## Тема: _Практичне застосування чисельних даних_
### Мета роботи: _застосувати практично чисельні дані_

---
### Виконання роботи

## Визначення однорідного масиву

In [2]:
def homework(message):
    print("\n>>>>>", message, "\n")

import numpy as np

# Список з кількома підсписками (матриця)
lst = [ [3.4, 8.7, 9.9], 
        [1.1, -7.8, -0.7],
        [4.1, 12.3, 4.8] ]

# Створення масиву з типом int8
A = np.array(lst, dtype=np.int8)
print(f"Масив A (тип int8) має вигляд:\n{repr(A)}")
# Пояснення: Масив A був створений з цілими числами, тип яких обмежений до 8 біт (від -128 до 127).
# Значення з плаваючою комою округлюються до найближчого цілого числа.

# Створення масиву з типом float16
B = np.array(lst, dtype=np.float16)
print(f"Масив B (тип float16) має вигляд:\n{repr(B)}")
# Пояснення: Масив B був створений з плаваючою комою, зберігаючи більше точності для дробових частин.
# Значення округлюються до 16 біт.

homework("Згадуючи ООП, що робить функція repr?")
print("Пояснення: Функція repr() повертає рядок, що є 'офіційною' або детальною репрезентацією об'єкта.")
print("Для масивів NumPy це зазвичай є вигляд масиву з його елементами, типом даних і розмірами.")

homework("У чому різниця між масивами A i B?")
print("Пояснення: Масив A має тип даних int8 (цілі числа), тому всі значення округлюються до цілих чисел.")
print("Масив B має тип float16 (плаваюча кома), тому він зберігає дробові числа з меншою точністю, але з більшою гнучкістю для роботи з такими числами.")


Масив A (тип int8) має вигляд:
array([[ 3,  8,  9],
       [ 1, -7,  0],
       [ 4, 12,  4]], dtype=int8)
Масив B (тип float16) має вигляд:
array([[ 3.4,  8.7,  9.9],
       [ 1.1, -7.8, -0.7],
       [ 4.1, 12.3,  4.8]], dtype=float16)

>>>>> Згадуючи ООП, що робить функція repr? 

Пояснення: Функція repr() повертає рядок, що є 'офіційною' або детальною репрезентацією об'єкта.
Для масивів NumPy це зазвичай є вигляд масиву з його елементами, типом даних і розмірами.

>>>>> У чому різниця між масивами A i B? 

Пояснення: Масив A має тип даних int8 (цілі числа), тому всі значення округлюються до цілих чисел.
Масив B має тип float16 (плаваюча кома), тому він зберігає дробові числа з меншою точністю, але з більшою гнучкістю для роботи з такими числами.


## Задаємо свій тип даних

In [3]:
def homework(message):
    print("\n>>>>>", message, "\n")

import numpy as np

# Створення dtype з іменами та оцінками
dt = np.dtype([('name', 'U20'), ('mark', np.int8)])  # 'U20' — це Unicode строка довжиною до 20 символів
arr = [
    ("Sofia", 5), 
    ("Maks", 4),
    ("Noname", 0)
]
C = np.array(arr, dtype=dt)

# Виведення масиву
print(f"Отриманий масив має вигляд:\n{C}")
# Доступ до колонки 'mark'
print(f"Доступитись до певної колонки тепер можна за її іменем: {C['mark']}")

# Виведення всіх імен
homework(f"Всі імена в масиві: {C['name']}")  # Виведення всіх імен

homework("Як вивести всі імена присутні в даному масиві?")
# Пояснення: Для того, щоб вивести всі імена, достатньо звернутись до колонки 'name' масиву C.
# Оскільки dtype масиву містить поле 'name', можна просто використовувати вираз C['name'] для доступу до всіх імен.
print("Пояснення: Для того, щоб вивести всі імена, достатньо звернутись до колонки 'name' масиву C.")
print("Оскільки dtype масиву містить поле 'name', можна просто використовувати вираз C['name'] для доступу до всіх імен.")


Отриманий масив має вигляд:
[('Sofia', 5) ('Maks', 4) ('Noname', 0)]
Доступитись до певної колонки тепер можна за її іменем: [5 4 0]

>>>>> Всі імена в масиві: ['Sofia' 'Maks' 'Noname'] 


>>>>> Як вивести всі імена присутні в даному масиві? 

Пояснення: Для того, щоб вивести всі імена, достатньо звернутись до колонки 'name' масиву C.
Оскільки dtype масиву містить поле 'name', можна просто використовувати вираз C['name'] для доступу до всіх імен.


## Запис та зчитування з файлу, формат CSV

In [4]:
import numpy as np
import os

# Створення dtype з додатковим полем 'group'
dt = np.dtype([('name', 'U20'), ('mark', np.int8), ('group', 'U10')])

# Масив з ім'ям, оцінкою та групою
arr = [
    ("Sofia", 5, "KN-41"),  # Замінив групу на "KN-41"
    ("Maks", 4, "KN-41"),
    ("Noname", 0, "KN-41"),
    ("Alina", 5, "KN-41")  # Додаємо ваше ім'я, оцінку та групу
]

# Створюємо масив з використанням нового dtype
C = np.array(arr, dtype=dt)

# Виводимо масив
print("Вихідний масив: ", C)

# Збереження в npz файл
np.savez("my_mass.npz", my_mass=C)

# Завантаження масиву з файлу
D = np.load("my_mass.npz")
print("Прочитаний з файлу: ", D["my_mass"])

# Записуємо в CSV файл
filename = "temp.csv"
print(f"Записуємо у CSV файл {filename} значення: {C}")
np.savetxt(filename, C, fmt="%s,%d,%s", header="name,mark,group", delimiter=",")

# Перевірка наявності файлу
print(f"Перевіряємо чи файл {filename} створився: {os.listdir()}")

# Читання файлу за допомогою оператора with та методу readlines
print("Читаємо файл за допомогою оператора with та методу readlines")
with open(filename) as f:
    D = f.readlines()

print(f"Прочитаний файл:\n {D} \n- як бачимо - {len(D)} елементи є стрічками {type(D[0])}.")

# Зчитуємо файл за допомогою np.genfromtxt
D = np.genfromtxt(filename, dtype=dt, delimiter=",", skip_header=1)  # пропускаємо перший рядок (заголовок)
print(f"Зчитане значення з файла:\n {D}, як бачимо - {D.size} елементи це {type(D[0])} \n- вбудований клас бібліотеки numpy.")

# Доступ до певного елемента
homework(f"Доступ до імені: {D[0]['name']}")  # Доступ до імені Софії

# Дописуємо код для виведення імені "Sofia" та її групи
sofia_info = C[C['name'] == 'Sofia']  # Знаходимо запис з ім'ям "Sofia"
sofia_name_group = sofia_info['name'][0], sofia_info['group'][0]  # Отримуємо ім'я та групу
homework(f"Ім'я: {sofia_name_group[0]}, Група: {sofia_name_group[1]}")  # Виводимо ім'я та групу

homework("Виведено значення імені та групи, яке було додано до масиву.")


Вихідний масив:  [('Sofia', 5, 'KN-41') ('Maks', 4, 'KN-41') ('Noname', 0, 'KN-41')
 ('Alina', 5, 'KN-41')]
Прочитаний з файлу:  [('Sofia', 5, 'KN-41') ('Maks', 4, 'KN-41') ('Noname', 0, 'KN-41')
 ('Alina', 5, 'KN-41')]
Записуємо у CSV файл temp.csv значення: [('Sofia', 5, 'KN-41') ('Maks', 4, 'KN-41') ('Noname', 0, 'KN-41')
 ('Alina', 5, 'KN-41')]
Перевіряємо чи файл temp.csv створився: ["numbers'methods2.ipynb", 'pictures', 'my_mass.npz', 'temp.csv', 'readme.md']
Читаємо файл за допомогою оператора with та методу readlines
Прочитаний файл:
 ['# name,mark,group\n', 'Sofia,5,KN-41\n', 'Maks,4,KN-41\n', 'Noname,0,KN-41\n', 'Alina,5,KN-41\n'] 
- як бачимо - 5 елементи є стрічками <class 'str'>.
Зчитане значення з файла:
 [('Sofia', 5, 'KN-41') ('Maks', 4, 'KN-41') ('Noname', 0, 'KN-41')
 ('Alina', 5, 'KN-41')], як бачимо - 4 елементи це <class 'numpy.void'> 
- вбудований клас бібліотеки numpy.

>>>>> Доступ до імені: Sofia 


>>>>> Ім'я: Sofia, Група: KN-41 


>>>>> Виведено значення іме

## Операції над масивами 

In [5]:
import numpy as np

l = (3, 3)

O = np.ones(l)
R = np.random.random(l)
Z = np.zeros(l)
C = np.arange(l[0])

print(f"""
Віднімання:\n {C - (O + 10)}
Множення:\n {O * R}
Ділення:\n {R / C}
Степінь:\n {C ** Z}
Порівняння:\n {R > 0.5}
Ділення на 0:\n {O / Z}
""")

homework("""
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де центральна діагональ буде 0).
""")

# Створення матриці одиничної матриці (eye) та перевірка на наявність одиничних елементів
E = np.eye(3)
print(f"""
Матриця eye:\n{E}
""")
print(f"""
Порівняння на наявність 1:\n{E == 1}
""")

# Створення матриці одиничних чисел (ones) та віднімання від неї матриці eye
ones_matrix = np.ones(l)
result = ones_matrix - E
print(f"""
Результат віднімання матриці eye від ones:\n{result}
""")



Віднімання:
 [[-11. -10.  -9.]
 [-11. -10.  -9.]
 [-11. -10.  -9.]]
Множення:
 [[0.01818432 0.88366905 0.4895086 ]
 [0.06133059 0.37373364 0.7539145 ]
 [0.64384195 0.87904022 0.96969883]]
Ділення:
 [[       inf 0.88366905 0.2447543 ]
 [       inf 0.37373364 0.37695725]
 [       inf 0.87904022 0.48484942]]
Степінь:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Порівняння:
 [[False  True False]
 [False False  True]
 [ True  True  True]]
Ділення на 0:
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


>>>>> 
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де центральна діагональ буде 0).
 


Матриця eye:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Порівняння на наявність 1:
[[ True False False]
 [False  True False]
 [False False  True]]


Результат віднімання матриці eye від ones:
[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]



/tmp/ipykernel_5672/3704401883.py:13: RuntimeWarning: divide by zero encountered in divide
  Ділення:\n {R / C}
/tmp/ipykernel_5672/3704401883.py:16: RuntimeWarning: divide by zero encountered in divide
  Ділення на 0:\n {O / Z}


## Конкатенація, повторення та зміна форми (shape)

In [6]:
import numpy as np

# 1. Створення двовимірного масиву за допомогою arange та виконання конкатенації та повторення
A = np.arange(6).reshape(2, 3)  # Масив 2x3
B = np.arange(6, 12).reshape(2, 3)  # Масив 2x3

print(f"Масив A:\n{A}")
print(f"Масив B:\n{B}")

# Конкатенація по рядках (axis=0)
concatenated_rows = np.concatenate((A, B), axis=0)
print(f"Конкатенація по рядках:\n{concatenated_rows}")

# Конкатенація по стовпцях (axis=1)
concatenated_columns = np.concatenate((A, B), axis=1)
print(f"Конкатенація по стовпцях:\n{concatenated_columns}")

# Повторення масиву A 2 рази по рядках і 3 рази по стовпцях
tiled = np.tile(A, (2, 3))
print(f"Повторення масиву A (2 рази по рядках і 3 рази по стовпцях):\n{tiled}")

# 2. Створення масиву з різною кількістю рядків та стовпців та конкатенація
C = np.arange(12).reshape(3, 4)  # Масив 3x4
print(f"Масив C:\n{C}")

# Зміна розміру масиву D на (3,1) і конкатенація з C по стовпцях
D = np.arange(3)  # Масив з розмірністю (3,)
print(f"Масив D (1D):\n{D}")
D_reshaped = D[:, np.newaxis]  # Перетворюємо D в (3,1)
print(f"Масив D після reshape (3,1):\n{D_reshaped}")

# Конкатенація C та D після reshape
concatenated_C_D = np.concatenate((C, D_reshaped), axis=1)
print(f"Конкатенація C та D по стовпцях:\n{concatenated_C_D}")

# 3. Створення кількох двовимірних масивів із сумарною розмірністю 12 та всі можливі комбінції reshape
E = np.arange(12).reshape(1, 12)  # Перша комбінація (1,12)
F = np.arange(12).reshape(3, 4)  # Друга комбінація (3,4)
G = np.arange(12).reshape(4, 3)  # Третя комбінація (4,3)
H = np.arange(12).reshape(2, 6)  # Четверта комбінація (2,6)

print(f"Масив E (1, 12):\n{E}")
print(f"Масив F (3, 4):\n{F}")
print(f"Масив G (4, 3):\n{G}")
print(f"Масив H (2, 6):\n{H}")


Масив A:
[[0 1 2]
 [3 4 5]]
Масив B:
[[ 6  7  8]
 [ 9 10 11]]
Конкатенація по рядках:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Конкатенація по стовпцях:
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]
Повторення масиву A (2 рази по рядках і 3 рази по стовпцях):
[[0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]]
Масив C:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Масив D (1D):
[0 1 2]
Масив D після reshape (3,1):
[[0]
 [1]
 [2]]
Конкатенація C та D по стовпцях:
[[ 0  1  2  3  0]
 [ 4  5  6  7  1]
 [ 8  9 10 11  2]]
Масив E (1, 12):
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
Масив F (3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Масив G (4, 3):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Масив H (2, 6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


## Трансформації масивів

In [7]:
import numpy as np

# 1. Створення вектора з 12 елементів
vector = np.arange(12)
print(f"1. Вектор з 12 елементів:\n{vector}")
print(f"   shape: {vector.shape}, size: {vector.size}, ndim: {vector.ndim}\n")

# 2. Зміна розмірності вектора у матрицю 3x4
matrix = vector.reshape(3, 4)
print(f"2. Матриця 3x4:\n{matrix}")
print(f"   shape: {matrix.shape}, size: {matrix.size}, ndim: {matrix.ndim}\n")

# 3. Транспонування матриці
transposed_matrix = matrix.T
print(f"3. Транспонована матриця:\n{transposed_matrix}")
print(f"   shape: {transposed_matrix.shape}, size: {transposed_matrix.size}, ndim: {transposed_matrix.ndim}\n")

# 4. Обертання матриці
flipped_matrix = np.flip(transposed_matrix)
print(f"4. Обернена матриця:\n{flipped_matrix}")
print(f"   shape: {flipped_matrix.shape}, size: {flipped_matrix.size}, ndim: {flipped_matrix.ndim}\n")

# 5. Перетворення багатовимірного масиву вектор
flattened = flipped_matrix.flatten()
print(f"5. Перетворений багатовимірний масив у вектор:\n{flattened}")
print(f"   shape: {flattened.shape}, size: {flattened.size}, ndim: {flattened.ndim}\n")


1. Вектор з 12 елементів:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
   shape: (12,), size: 12, ndim: 1

2. Матриця 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
   shape: (3, 4), size: 12, ndim: 2

3. Транспонована матриця:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
   shape: (4, 3), size: 12, ndim: 2

4. Обернена матриця:
[[11  7  3]
 [10  6  2]
 [ 9  5  1]
 [ 8  4  0]]
   shape: (4, 3), size: 12, ndim: 2

5. Перетворений багатовимірний масив у вектор:
[11  7  3 10  6  2  9  5  1  8  4  0]
   shape: (12,), size: 12, ndim: 1



#### 7 завдання

1. Метод arange
- :question: Метод arange генерує числову послідовність на основі початкового значення, кінцевого значення та кроку
> Формула для цього виглядає так: a(n)=a(0)+n*d
- :question: Формула вказує, що наступний елемент послідовності генерується шляхом додавання кроку до попереднього елемента.
**### Приклад**:

In [8]:
import numpy as np
a = np.arange(1, 10, 2)
print(a)

[1 3 5 7 9]


2. Метод linspace
- :question: Метод linspace генерує числову послідовність, вказуючи початкове та кінцеве значення, а також кількість елементів. Він автоматично обчислює крок для рівномірного розподілу елементів між початком і кінцем. 
> Формула для цього виглядає так: a(n)=(a(0)+a(T)-a(0)/N-1)*n; де - a(0)— початкове значення, 𝑎(Т)— кінцеве значення, N— кількість елементів, n — індекс елемента (від 0 до N−1).
- :question: Формула вказує, що крок обчислюється так, щоб числа рівномірно заповнили весь діапазон від a(0) до а(Т)

### **Приклад**

In [9]:
import numpy as np
b = np.linspace(1, 10, 5)
print(b)

[ 1.    3.25  5.5   7.75 10.  ]


## Порівняння формул і випадків використання

> Формули:
> - У `arange` крок 𝑑 є постійним, а ми визначаємо тільки початкове значення та кінцеве значення (яке може не бути включене в результат).
> - У `linspace` кількість елементів N є постійною, і крок обчислюється таким чином, щоб рівномірно розподілити значення від початку до кінця.
> Коли використовувати які методи:
> - `arange` застосовується, коли вам потрібно працювати з конкретним кроком (різницею між елементами). Це корисно, коли ви хочете, щоб послідовність мала певну інтервалу (наприклад, у часових серіях або у фізичних розрахунках).
> - - **Приклад**: крок 0.5 між значеннями, або інтервал між чисел певного типу.
> - `linspace` застосовується, коли вам потрібно рівномірно розподілити задану кількість точок між двома значеннями, і важливо точно визначити кількість елементів у послідовності.
> - - **Приклад**: для графіків, де потрібно рівномірно розподілити точки на осі або при чисельних методах, де кількість точок має бути заданою наперед.
##### Висновок:
> - `arange `підходить для генерації послідовностей з конкретним кроком, коли вам важливо контролювати інтервал між елементами.
> - `linspace` підходить для ситуацій, коли потрібно рівномірно розподілити задану кількість елементів між початковим і кінцевим значенням, гарантуючи, що всі значення будуть рівномірно розподілені.
Ці методи використовуються в залежності від задачі: `arange` зручний для послідовностей з фіксованим кроком, а `linspace` — для рівномірного розподілу значень на заданому інтервалі.


### Створюю декілька простих Векторів та Матриць та виведжу їх розмірність. Виконую арифметичні операції над створеними Векторам/Матрицями;

**1. Створення простих векторів та матриць**

In [10]:
import numpy as np

# Створюю вектор-рядок та вектор-стовпець
vector_row = np.array([1, 2, 3, 4, 5])
vector_column = np.array([[1], [2], [3], [4], [5]])

# Створюю матрицю 2x3
matrix_2x3 = np.array([[1, 2, 3], [4, 5, 6]])

# Створюю матрицю 3x3
matrix_3x3 = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])

# Виводжу розмірність
print("Розмірність вектора-рядка:", vector_row.shape)
print("Розмірність вектора-стовпця:", vector_column.shape)
print("Розмірність матриці 2x3:", matrix_2x3.shape)
print("Розмірність матриці 3x3:", matrix_3x3.shape)

Розмірність вектора-рядка: (5,)
Розмірність вектора-стовпця: (5, 1)
Розмірність матриці 2x3: (2, 3)
Розмірність матриці 3x3: (3, 3)


**2. Арифметичні операції над векторами та матрицями**
> Операції з векторами

In [11]:
# Додавання векторів
vector_add = vector_row + np.array([1, 1, 1, 1, 1])
print("\nДодавання векторів:\n", vector_add)

# Множення вектора на скаляр
vector_multiply = vector_row * 2
print("\nМноження вектора на скаляр:\n", vector_multiply)

# Віднімання векторів
vector_subtract = vector_row - np.array([0, 1, 2, 3, 4])
print("\nВіднімання векторів:\n", vector_subtract)


Додавання векторів:
 [2 3 4 5 6]

Множення вектора на скаляр:
 [ 2  4  6  8 10]

Віднімання векторів:
 [1 1 1 1 1]


> Операції з матрицями

In [12]:
# Додавання матриць
matrix_add = matrix_3x3 + np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
print("\nДодавання матриць:\n", matrix_add)

# Множення матриці на скаляр
matrix_multiply = matrix_3x3 * 3
print("\nМноження матриці на скаляр:\n", matrix_multiply)

# Транспонування матриці
matrix_transpose = matrix_3x3.T
print("\nТранспонування матриці:\n", matrix_transpose)


Додавання матриць:
 [[ 8  9 10]
 [11 12 13]
 [14 15 16]]

Множення матриці на скаляр:
 [[21 24 27]
 [30 33 36]
 [39 42 45]]

Транспонування матриці:
 [[ 7 10 13]
 [ 8 11 14]
 [ 9 12 15]]


---

### Висновок:

> відповідаю на запитання:

- :question: Що зроблено в роботі;
  > Практичне застосування чисельних даних
- :question: Чи досягнуто мети роботи;
  > я, думаю, досягнуто
- :question: Які нові знання отримано;
  > Трансформації масивів, конкатенація, повторення та зміна форми (shape), 
- :question: Чи вдалось відповісти на всі питання задані в ході роботи;
  > наче, так
- :question: Чи вдалося виконати всі завдання;
  > якшо я нічого не пропустила-то так)
- :question: Чи виникли складності у виконанні завдання;
  > навіть якшо були, то вже немає, після чорної полоси завжди буле біла :point_up_2:
- :question: Чи подобається такий формат здачі роботи (Feedback);
  > Дуже, прикольний вигляд має та неорлинарний, відчуваю себе надпрограмістом :joy:
- :question: Побажання для покращення (Suggestions);
  > поки що все подобається)

---
